import { describe, expect, test } from "bun:test";
import {
  parseDiffAddedLines,
  runTier0Checkers,
  createDefaultHelpers,
  type Tier0Helpers,
} from "./tier0-checkers.ts";
import type { CommitContext } from "./commit-validators.ts";

const ctx = (over: Partial<CommitContext> = {}): CommitContext => ({
  diff: "",
  files: [],
  message: "",
  command: "git commit -m \"x\"",
  cwd: "/tmp",
  ...over,
});

function result(names: string[], context: CommitContext, helpers?: Tier0Helpers) {
  const out = runTier0Checkers(names, context, helpers);
  const byName = new Map(out.map((r) => [r.validator, r]));
  return { out, byName };
}

describe("parseDiffAddedLines", () => {
  test("multi-file buckets", () => {
    const diff = `diff --git a/a.ts b/a.ts
--- a/a.ts
+++ b/a.ts
@@ -1 +1,2 @@
+lineA1
+lineA2
diff --git a/b.ts b/b.ts
--- a/b.ts
+++ b/b.ts
@@ -1 +1 @@
+lineB1
`;
    const m = parseDiffAddedLines(diff);
    expect([...m.keys()]).toEqual(["a.ts", "b.ts"]);
    expect(m.get("a.ts")).toEqual(["lineA1", "lineA2"]);
    expect(m.get("b.ts")).toEqual(["lineB1"]);
  });

  test("/dev/null deletion yields no bucket", () => {
    const diff = `diff --git a/gone.ts b/gone.ts
--- a/gone.ts
+++ /dev/null
@@ -1,2 +0,0 @@
-old1
-old2
`;
    expect([...parseDiffAddedLines(diff).keys()]).toEqual([]);
  });

  test("+++ / --- header lines not treated as added content", () => {
    const diff = `diff --git a/x.ts b/x.ts
--- a/x.ts
+++ b/x.ts
@@ -1 +1,2 @@
+real
`;
    const m = parseDiffAddedLines(diff);
    expect(m.get("x.ts")).toEqual(["real"]);
  });
});

describe("no-dangerous-git", () => {
  test("NACK on --no-verify", () => {
    const c = ctx({ command: "git commit --no-verify -m x" });
    expect(result(["no-dangerous-git"], c).byName.get("no-dangerous-git")).toEqual({
      validator: "no-dangerous-git",
      decision: "NACK",
      reason: expect.stringContaining("--no-verify"),
    });
  });

  test("ACK on safe commit", () => {
    const c = ctx({ command: "git commit -m ok" });
    expect(result(["no-dangerous-git"], c).byName.get("no-dangerous-git")?.decision).toBe("ACK");
  });
});

describe("hygiene", () => {
  test("NACK on .js outside dist/", () => {
    const c = ctx({ files: ["lib.js"] });
    expect(result(["hygiene"], c).byName.get("hygiene")?.decision).toBe("NACK");
  });

  test("ACK on clean files and message", () => {
    const c = ctx({ files: ["dist/bundle.js", "src/a.ts"], message: "feat: x" });
    expect(result(["hygiene"], c).byName.get("hygiene")?.decision).toBe("ACK");
  });

  test("NACK on claude attribution", () => {
    const c = ctx({ message: "generated by claude" });
    expect(result(["hygiene"], c).byName.get("hygiene")?.decision).toBe("NACK");
  });
});

describe("coverage-rules", () => {
  test("NACK on ts-ignore in source", () => {
    const c = ctx({
      diff: `diff --git a/src/a.ts b/src/a.ts
--- a/src/a.ts
+++ b/src/a.ts
@@ -1 +1,2 @@
+// @ts-ignore
+const x = 1;
`,
    });
    expect(result(["coverage-rules"], c).byName.get("coverage-rules")?.decision).toBe("NACK");
  });

  test("NACK on 'any' type annotation", () => {
    const c = ctx({
      diff: `diff --git a/src/a.ts b/src/a.ts
--- a/src/a.ts
+++ b/src/a.ts
@@ -1 +1,2 @@
+function f(x: any) { return x; }
`,
    });
    expect(result(["coverage-rules"], c).byName.get("coverage-rules")?.decision).toBe("NACK");
  });

  test("ACK on test-file escape hatch (exempt)", () => {
    const c = ctx({
      diff: `diff --git a/src/a.test.ts b/src/a.test.ts
--- a/src/a.test.ts
+++ b/src/a.test.ts
@@ -1 +1,2 @@
+// @ts-ignore
+expect(1).toBe(1);
`,
    });
    expect(result(["coverage-rules"], c).byName.get("coverage-rules")?.decision).toBe("ACK");
  });

  test("ACK when clean", () => {
    const c = ctx({
      diff: `diff --git a/src/a.ts b/src/a.ts
--- a/src/a.ts
+++ b/src/a.ts
@@ -1 +1,2 @@
+const x: number = 1;
`,
    });
    expect(result(["coverage-rules"], c).byName.get("coverage-rules")?.decision).toBe("ACK");
  });
});

describe("type-organization", () => {
  test("NACK on standalone types.ts", () => {
    const c = ctx({ files: ["types.ts"] });
    expect(result(["type-organization"], c).byName.get("type-organization")?.decision).toBe("NACK");
  });

  test("ACK on inline types", () => {
    const c = ctx({ files: ["src/a.ts"] });
    expect(result(["type-organization"], c).byName.get("type-organization")?.decision).toBe("ACK");
  });
});

describe("testing-weak-assertions", () => {
  test("NACK on toBeTruthy in test file", () => {
    const c = ctx({
      diff: `diff --git a/src/a.test.ts b/src/a.test.ts
--- a/src/a.test.ts
+++ b/src/a.test.ts
@@ -1 +1,2 @@
+expect(x).toBeTruthy();
`,
    });
    expect(result(["testing-weak-assertions"], c).byName.get("testing-weak-assertions")?.decision).toBe("NACK");
  });

  test("ACK on strong assertion", () => {
    const c = ctx({
      diff: `diff --git a/src/a.test.ts b/src/a.test.ts
--- a/src/a.test.ts
+++ b/src/a.test.ts
@@ -1 +1,2 @@
+expect(x).toBe(3);
`,
    });
    expect(result(["testing-weak-assertions"], c).byName.get("testing-weak-assertions")?.decision).toBe("ACK");
  });
});

describe("infra-commit-format", () => {
  test("NACK on config-only commit with feat:", () => {
    const c = ctx({
      files: ["package.json"],
      message: "feat: bump dep",
    });
    expect(result(["infra-commit-format"], c).byName.get("infra-commit-format")?.decision).toBe("NACK");
  });

  test("ACK on config-only commit with chore:", () => {
    const c = ctx({
      files: ["package.json"],
      message: "chore: bump dep",
    });
    expect(result(["infra-commit-format"], c).byName.get("infra-commit-format")?.decision).toBe("ACK");
  });

  test("ACK when behavioral source present", () => {
    const c = ctx({
      files: ["src/a.ts", "package.json"],
      message: "feat: x",
    });
    expect(result(["infra-commit-format"], c).byName.get("infra-commit-format")?.decision).toBe("ACK");
  });
});

describe("commit-message-no-speculation", () => {
  test("NACK on 'should work'", () => {
    const c = ctx({ message: "this should work" });
    expect(result(["commit-message-no-speculation"], c).byName.get("commit-message-no-speculation")?.decision).toBe("NACK");
  });

  test("NACK on 'fixes?'", () => {
    const c = ctx({ message: "fixes? the bug" });
    expect(result(["commit-message-no-speculation"], c).byName.get("commit-message-no-speculation")?.decision).toBe("NACK");
  });

  test("ACK on factual message", () => {
    const c = ctx({ message: "feat: add validation to commit flow" });
    expect(result(["commit-message-no-speculation"], c).byName.get("commit-message-no-speculation")?.decision).toBe("ACK");
  });
});

describe("ketchup-plan-format", () => {
  const helpers: Tier0Helpers = {
    readStagedFile: () => null,
  };

  test("ACK when ketchup-plan.md not in files", () => {
    const c = ctx({ files: ["src/a.ts"] });
    expect(result(["ketchup-plan-format"], c, helpers).byName.get("ketchup-plan-format")?.decision).toBe("ACK");
  });

  test("NACK on missing TODO section (stub returns content)", () => {
    const h: Tier0Helpers = {
      readStagedFile: () => "# plan\n## DONE\n- x\n",
    };
    const c = ctx({ files: ["ketchup-plan.md"] });
    expect(result(["ketchup-plan-format"], c, h).byName.get("ketchup-plan-format")?.decision).toBe("NACK");
  });

  test("ACK on well-formed plan (stub returns content)", () => {
    const h: Tier0Helpers = {
      readStagedFile: () => "# plan\n## TODO\n- [ ] Burst one [depends: none]\n## DONE\n- [x] Burst zero [depends: none]\n",
    };
    const c = ctx({ files: ["ketchup-plan.md"] });
    expect(result(["ketchup-plan-format"], c, h).byName.get("ketchup-plan-format")?.decision).toBe("ACK");
  });
});

describe("runTier0Checkers", () => {
  test("unknown name NACKs not implemented", () => {
    const c = ctx();
    expect(result(["bogus"], c).byName.get("bogus")).toEqual({
      validator: "bogus",
      decision: "NACK",
      reason: "tier-0 checker 'bogus' is not implemented",
    });
  });

  test("createDefaultHelpers.readStagedFile returns null on absent path", () => {
    const h = createDefaultHelpers("/tmp");
    expect(h.readStagedFile("definitely-not-staged-xyz.ts")).toBeNull();
  });
});