import { execFileSync } from "node:child_process";
import type { CommitContext } from "./commit-validators.ts";

export interface CheckerResult {
  decision: "ACK" | "NACK";
  reason?: string;
}

export type Tier0Checker = (
  context: CommitContext,
  helpers: Tier0Helpers,
) => CheckerResult;

export interface Tier0Helpers {
  readStagedFile: (relPath: string) => string | null;
}

export function createDefaultHelpers(cwd: string): Tier0Helpers {
  return {
    readStagedFile: (relPath) => {
      try {
        return execFileSync("git", ["show", `:${relPath}`], {
          cwd,
          encoding: "utf8",
          stdio: ["ignore", "pipe", "ignore"],
        });
      } catch {
        return null;
      }
    },
  };
}

export const TIER0_CHECKERS: Record<string, Tier0Checker> = {
  "no-dangerous-git": checkNoDangerousGit,
  hygiene: checkHygiene,
  "coverage-rules": checkCoverageRules,
  "type-organization": checkTypeOrganization,
  "testing-weak-assertions": checkTestingWeakAssertions,
  "infra-commit-format": checkInfraCommitFormat,
  "commit-message-no-speculation": checkCommitMessageNoSpeculation,
  "ketchup-plan-format": checkKetchupPlanFormat,
};

export function runTier0Checkers(
  names: string[],
  context: CommitContext,
  helpers?: Tier0Helpers,
): { validator: string; decision: "ACK" | "NACK"; reason?: string }[] {
  const h = helpers ?? createDefaultHelpers(context.cwd);
  return names.map((name) => {
    const checker = TIER0_CHECKERS[name];
    if (!checker) {
      return {
        validator: name,
        decision: "NACK",
        reason: `tier-0 checker '${name}' is not implemented`,
      };
    }
    const result = checker(context, h);
    return {
      validator: name,
      decision: result.decision,
      reason: result.reason,
    };
  });
}

export function parseDiffAddedLines(diff: string): Map<string, string[]> {
  const result = new Map<string, string[]>();
  let current: string | null = null;
  let currentAdded: string[] = [];

  const flush = () => {
    if (current !== null) result.set(current, currentAdded);
    current = null;
    currentAdded = [];
  };

  for (const line of diff.split("\n")) {
    if (line.startsWith("diff --git")) {
      flush();
      continue;
    }
    if (line.startsWith("+++ ")) {
      flush();
      current = line.slice(4).replace(/^b\//, "");
      if (current === "/dev/null") current = null;
      continue;
    }
    if (line.startsWith("--- ")) {
      continue;
    }
    if (current !== null && line.startsWith("+") && !line.startsWith("+++")) {
      currentAdded.push(line.slice(1));
    }
  }
  flush();
  return result;
}

const TS_EXT = /\.(ts|tsx)$/;
const TEST_FILE = /\.(test|spec)\.(ts|tsx)$/;
const JS_EXT = /\.(js|jsx)$/;

function isBarrelIndex(file: string): boolean {
  return /(^|\/)index\.(ts|tsx)$/.test(file);
}

function isTypeFile(file: string): boolean {
  const base = file.split("/").pop() ?? "";
  if (/^(types|interfaces)\.(ts|tsx)$/.test(base)) return true;
  if (/^types\//.test(file) || /\/types\//.test(file)) return true;
  if (/^interfaces\//.test(file) || /\/interfaces\//.test(file)) return true;
  return false;
}

const nack = (reason: string): CheckerResult => ({ decision: "NACK", reason });
const ack = (): CheckerResult => ({ decision: "ACK" });

function checkNoDangerousGit(context: CommitContext): CheckerResult {
  const command = context.command ?? "";
  const dangerous: RegExp[] = [
    /--no-verify\b/,
    /--force\b/,
    /--force-with-lease\b/,
    /\s-f\b/,
    /--amend\b/,
    /reset\s+--hard\b/,
  ];
  for (const re of dangerous) {
    if (re.test(command)) {
      return nack(`commit command uses a forbidden git flag (${re.source})`);
    }
  }
  return ack();
}

function checkHygiene(context: CommitContext): CheckerResult {
  for (const file of context.files) {
    if (
      JS_EXT.test(file) &&
      !file.startsWith("dist/") &&
      !file.includes("/dist/")
    ) {
      return nack(
        `.js file outside dist/ is not allowed: ${file} (source should be .ts)`,
      );
    }
  }

  const msg = context.message;
  const attribution = [
    /co-authored-by:[^\n]*claude/i,
    /generated with claude/i,
    /generated by claude/i,
    /\bclaude\b/i,
    /generated with (?:a\.?i\.?|gpt|copilot|gemini|llm)/i,
    /generated by (?:a\.?i\.?|gpt|copilot|gemini|llm)/i,
  ];
  for (const re of attribution) {
    if (re.test(msg)) {
      return nack("commit message contains AI/LLM attribution");
    }
  }
  return ack();
}

function checkCoverageRules(context: CommitContext): CheckerResult {
  const addedByFile = parseDiffAddedLines(context.diff);

  for (const [file, lines] of addedByFile) {
    if (!TS_EXT.test(file)) continue;
    if (TEST_FILE.test(file)) continue;
    if (isBarrelIndex(file)) continue;

    for (const line of lines) {
      if (/@ts-ignore|@ts-expect-error/.test(line)) {
        return nack(`ts-ignore/ts-expect-error escape hatch in ${file}`);
      }
      if (/\/\*\s*(istanbul|c8|v8)\s+ignore/.test(line)) {
        return nack(`coverage-ignore pragma in ${file}`);
      }
      if (/(^|[^A-Za-z0-9_$])any(?=[\s,>;)[\]=]|$)/.test(line)) {
        return nack(`'any' type annotation in ${file}`);
      }
      if (/\bas\s+unknown\s+as\b/.test(line)) {
        return nack(`'as unknown as' cast in ${file}`);
      }
    }
  }
  return ack();
}

function checkTypeOrganization(context: CommitContext): CheckerResult {
  for (const file of context.files) {
    if (isTypeFile(file)) {
      return nack(
        `standalone type file '${file}' — define types inline where used`,
      );
    }
  }
  return ack();
}

function checkTestingWeakAssertions(context: CommitContext): CheckerResult {
  const addedByFile = parseDiffAddedLines(context.diff);
  const weak = [
    /\.toBeDefined\(\)/,
    /\.toBeTruthy\(\)/,
    /\.toBeFalsy\(\)/,
    /\.not\.toBeNull\(\)/,
    /\.not\.toBeUndefined\(\)/,
    /\.toBeGreaterThan\(0\)/,
  ];

  for (const [file, lines] of addedByFile) {
    if (!TEST_FILE.test(file)) continue;
    for (const line of lines) {
      for (const re of weak) {
        if (re.test(line)) {
          return nack(`weak assertion ${re.source} in ${file}`);
        }
      }
    }
  }
  return ack();
}

const CONFIG_FILE =
  /^(package\.json|package-lock\.json|pnpm-lock\.yaml|yarn\.lock|tsconfig.*\.json|\w+\.config\.(ts|js|mts|cjs|mjs)|wrangler\.toml|\.gitignore|\.npmignore|\.eslintrc.*|\.prettierrc.*|\.editorconfig|.*\.lock|.*\.toml|.*\.ya?ml|.*\.json)$/;

const CONFIG_DIR = /^(\.claude|\.github|\.vscode|\.idea)\//;

function isConfigFile(file: string): boolean {
  if (CONFIG_DIR.test(file)) return true;
  return CONFIG_FILE.test(file);
}

function checkInfraCommitFormat(context: CommitContext): CheckerResult {
  if (context.files.length === 0) return ack();

  const hasBehavioral = context.files.some(
    (f) => TS_EXT.test(f) && !/\.(config)\.(ts|js)$/.test(f),
  );
  if (hasBehavioral) return ack();

  const allConfig = context.files.every(isConfigFile);
  if (!allConfig) return ack();

  const subject = context.message.split("\n")[0].trim();
  if (/^(feat|fix|test|build|ci|refactor|perf)(\(.+\))?:/.test(subject)) {
    if (!/^chore(\(.+\))?:/.test(subject)) {
      return nack(
        `config-only commit should use 'chore:' not '${subject.split(":")[0]}:'`,
      );
    }
  }
  return ack();
}

const SPECULATION_PHRASES = [
  "should work",
  "should pass",
  "should fix",
  "should be fine",
  "probably",
  "seems to",
  "seems fine",
  "i think",
  "might work",
  "might fix",
  "maybe",
  "hopefully",
  "fingers crossed",
  "let's see",
  "let's try",
  "trying this",
  "try this",
  "not sure if",
  "not 100%",
  "uncertain",
  "untested but",
];

function checkCommitMessageNoSpeculation(context: CommitContext): CheckerResult {
  const lower = context.message.toLowerCase();
  for (const phrase of SPECULATION_PHRASES) {
    if (lower.includes(phrase)) {
      return nack(`speculative language in commit message: '${phrase}'`);
    }
  }
  if (/\b(fix|fixes|fixed|works|worked)\s*\?/.test(lower)) {
    return nack("speculative '?' after a claim in commit message");
  }
  return ack();
}

function checkKetchupPlanFormat(
  context: CommitContext,
  helpers: Tier0Helpers,
): CheckerResult {
  if (!context.files.includes("ketchup-plan.md")) return ack();

  const content = helpers.readStagedFile("ketchup-plan.md");
  if (content === null) {
    return ack();
  }

  if (!/^##\s+TODO\b/m.test(content)) {
    return nack("ketchup-plan.md is missing a '## TODO' section");
  }
  if (!/^##\s+DONE\b/m.test(content)) {
    return nack("ketchup-plan.md is missing a '## DONE' section");
  }

  if (/^###\s+Bottle\s+\d+/m.test(content)) {
    return nack(
      "ketchup-plan.md names a bottle by number — use a capability name",
    );
  }

  const placeholders = [
    /\bTBD\b/,
    /\bTODO:/,
    /\bFIXME\b/,
    /\bXXX\b/,
    /<placeholder>/i,
    /<fill in>/i,
    /\?\?\?/,
    /\[depends:\s*TBD\]/i,
  ];
  for (const re of placeholders) {
    if (re.test(content)) {
      return nack(
        `ketchup-plan.md contains placeholder content (${re.source})`,
      );
    }
  }

  const burstLines = content
    .split("\n")
    .filter((l) => /^-\s+\[[ xX]\]\s+Burst\b/.test(l));
  for (const line of burstLines) {
    if (!/\[depends:/.test(line)) {
      return nack(
        "ketchup-plan.md has a burst missing '[depends: ...]' notation",
      );
    }
  }

  return ack();
}